export type Crop = {
  id: string;
  name_en: string;
  name_ur: string;
  name_roman: string;
  aliases: string[];
  scientific: string;
  emoji: string;
  category: "Cereal" | "Cash" | "Vegetable" | "Fruit" | "Pulse" | "Oilseed";
  provinces: string[];
  districts: string[];
  sowing: string;
  harvest: string;
  temperature: string;
  rainfall: string;
  soil: string;
  fertilizer: string;
  irrigation: string;
  weed: string;
  pest: string;
  disease: string;
  yield: string;
  storage: string;
  market: string;
  image: string; // unsplash query
};

const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=800&q=70`;

export const CROPS: Crop[] = [
  {
    id: "wheat",
    name_en: "Wheat",
    name_ur: "گندم",
    name_roman: "Gandum",
    aliases: ["gehun", "kanak", "gandom"],
    scientific: "Triticum aestivum",
    emoji: "🌾",
    category: "Cereal",
    provinces: ["Punjab", "Sindh", "KPK", "Balochistan"],
    districts: ["Faisalabad", "Multan", "Sahiwal", "Bahawalpur", "Sukkur"],
    sowing: "November – December (Rabi)",
    harvest: "April – May",
    temperature: "10–25 °C",
    rainfall: "300–400 mm",
    soil: "Well-drained loamy to clay-loam, pH 6.0–7.5",
    fertilizer: "Urea 2 bags + DAP 1 bag + SOP 0.5 bag per acre; split N: 1/3 at sowing, 1/3 at 1st irrigation, 1/3 at 2nd.",
    irrigation: "4–6 irrigations: crown-root (20–25 DAS), tillering, jointing, booting, milking, dough.",
    weed: "Pre-emergence Pendimethalin or post-emergence Bromoxynil + MCPA for broadleaf; Clodinafop for grassy weeds.",
    pest: "Aphids, armyworm — spray Imidacloprid 200 SL @ 100 ml/acre when threshold crossed.",
    disease: "Yellow rust, leaf rust, loose smut — use resistant varieties; Tebuconazole 250 EC @ 200 ml/acre.",
    yield: "35–50 maunds/acre with good management",
    storage: "Dry to 10% moisture; fumigate with aluminum phosphide in sealed silos.",
    market: "Support price announced yearly by Government of Pakistan; consistent domestic demand.",
    image: img("photo-1574323347407-f5e1ad6d020b"),
  },
  {
    id: "cotton",
    name_en: "Cotton",
    name_ur: "کپاس",
    name_roman: "Kapaas",
    aliases: ["kapas", "phutti", "cotton plant"],
    scientific: "Gossypium hirsutum",
    emoji: "🌱",
    category: "Cash",
    provinces: ["Punjab", "Sindh"],
    districts: ["Multan", "Bahawalpur", "Rahim Yar Khan", "Sanghar", "Mirpur Khas"],
    sowing: "April – May (Kharif)",
    harvest: "September – December",
    temperature: "21–30 °C",
    rainfall: "500–1000 mm (with irrigation)",
    soil: "Deep well-drained sandy loam, pH 6.5–8.0",
    fertilizer: "Urea 3 bags + DAP 1 bag + SOP 1 bag per acre; N in 3 splits.",
    irrigation: "6–8 irrigations at 12–15 day intervals; critical at flowering & boll formation.",
    weed: "Pre-emergence S-metolachlor; hand hoeing at 25 & 45 DAS.",
    pest: "Whitefly, pink bollworm, thrips — use IPM, pheromone traps, and rotational sprays.",
    disease: "Cotton Leaf Curl Virus (CLCuV), fusarium wilt — sow resistant Bt varieties.",
    yield: "25–35 maunds/acre",
    storage: "Store phutti in dry ventilated rooms; avoid moisture.",
    market: "Exported as raw cotton and yarn; prices linked to New York cotton futures.",
    image: img("photo-1594906855260-f13a5b3c0d4a"),
  },
  {
    id: "rice",
    name_en: "Rice",
    name_ur: "چاول",
    name_roman: "Chawal",
    aliases: ["basmati", "dhaan", "paddy"],
    scientific: "Oryza sativa",
    emoji: "🍚",
    category: "Cereal",
    provinces: ["Punjab", "Sindh"],
    districts: ["Gujranwala", "Sheikhupura", "Sialkot", "Larkana", "Thatta"],
    sowing: "May – July (nursery), transplant June – July",
    harvest: "October – November",
    temperature: "20–35 °C",
    rainfall: "1000–2000 mm equivalent (flooded)",
    soil: "Heavy clay-loam with good water retention, pH 5.5–7.0",
    fertilizer: "Urea 3 bags + DAP 1 bag + Zinc Sulphate 5 kg per acre.",
    irrigation: "Standing water 5 cm through vegetative; drain 10 days before harvest.",
    weed: "Butachlor pre-emergence; hand weeding for sedges.",
    pest: "Rice stem borer, leaf folder — Cartap Hydrochloride @ 250 g/acre.",
    disease: "Blast, bacterial leaf blight — use certified seed & Tricyclazole.",
    yield: "40–60 maunds/acre (Basmati 30–40)",
    storage: "Dry to 12–14% moisture; store in jute bags.",
    market: "Basmati is a major export earner; premium price in Middle East & EU.",
    image: img("photo-1536304993881-ff6e9eefa2a6"),
  },
  {
    id: "sugarcane",
    name_en: "Sugarcane",
    name_ur: "گنا",
    name_roman: "Ganna",
    aliases: ["kamad", "sugar cane"],
    scientific: "Saccharum officinarum",
    emoji: "🎋",
    category: "Cash",
    provinces: ["Punjab", "Sindh", "KPK"],
    districts: ["Faisalabad", "Jhang", "Badin", "Thatta", "Charsadda"],
    sowing: "February – March (spring) or September – October (autumn)",
    harvest: "November – March",
    temperature: "20–35 °C",
    rainfall: "1100–1500 mm equivalent",
    soil: "Deep loamy well-drained, pH 6.5–7.5",
    fertilizer: "Urea 5 bags + DAP 2 bags + SOP 1 bag per acre.",
    irrigation: "15–20 irrigations; critical at tillering & grand growth.",
    weed: "Atrazine pre-emergence + earthing up at 90 DAS.",
    pest: "Top borer, pyrilla — release Trichogramma; spray Chlorpyrifos if needed.",
    disease: "Red rot, smut — use disease-free setts and resistant varieties.",
    yield: "600–900 maunds/acre",
    storage: "Harvest close to crushing; sucrose drops within 48 h.",
    market: "Government sets minimum sugarcane price; sold to sugar mills.",
    image: img("photo-1596040033229-a9821ebd058d"),
  },
  {
    id: "maize",
    name_en: "Maize",
    name_ur: "مکئی",
    name_roman: "Makai",
    aliases: ["corn", "makki", "bhutta"],
    scientific: "Zea mays",
    emoji: "🌽",
    category: "Cereal",
    provinces: ["Punjab", "KPK"],
    districts: ["Okara", "Sahiwal", "Swat", "Mardan", "Chitral"],
    sowing: "Spring: Jan–Feb; Autumn: July–August",
    harvest: "June (spring) / October–Nov (autumn)",
    temperature: "18–32 °C",
    rainfall: "500–800 mm",
    soil: "Well-drained loamy, pH 5.8–7.0",
    fertilizer: "Urea 3 bags + DAP 1.5 bags + SOP 0.5 bag per acre.",
    irrigation: "5–7 irrigations; critical at tasseling & silking.",
    weed: "Atrazine + S-metolachlor pre-emergence.",
    pest: "Fall armyworm — Emamectin benzoate @ 100 g/acre when 5% infestation.",
    disease: "Downy mildew, leaf blight — seed treatment with Metalaxyl.",
    yield: "60–90 maunds/acre for hybrids",
    storage: "Dry to 13% moisture; store in silos or dry sheds.",
    market: "Strong demand from poultry feed & starch industry.",
    image: img("photo-1601472544365-8d956e5c8f8f"),
  },
  {
    id: "potato",
    name_en: "Potato",
    name_ur: "آلو",
    name_roman: "Aloo",
    aliases: ["alu", "potato tuber"],
    scientific: "Solanum tuberosum",
    emoji: "🥔",
    category: "Vegetable",
    provinces: ["Punjab", "KPK", "Gilgit-Baltistan"],
    districts: ["Okara", "Sahiwal", "Kasur", "Skardu"],
    sowing: "Autumn: Sep–Oct; Spring: Jan–Feb",
    harvest: "Feb–Mar (autumn) / May (spring)",
    temperature: "15–25 °C",
    rainfall: "500–700 mm",
    soil: "Sandy loam rich in organic matter, pH 5.5–6.5",
    fertilizer: "Urea 2.5 bags + DAP 2 bags + SOP 2 bags per acre.",
    irrigation: "8–10 light irrigations; avoid water-logging.",
    weed: "Metribuzin pre-emergence + earthing up at 30 & 45 DAS.",
    pest: "Aphids, cutworm — Imidacloprid or Chlorpyrifos as required.",
    disease: "Late blight — Mancozeb + Metalaxyl weekly during humid weather.",
    yield: "200–300 maunds/acre",
    storage: "Cold store at 2–4 °C & 90% humidity to reduce sprouting.",
    market: "High domestic + export demand to Afghanistan, UAE.",
    image: img("photo-1518977676601-b53f82aba655"),
  },
  {
    id: "tomato",
    name_en: "Tomato",
    name_ur: "ٹماٹر",
    name_roman: "Tamatar",
    aliases: ["timatar", "tamater"],
    scientific: "Solanum lycopersicum",
    emoji: "🍅",
    category: "Vegetable",
    provinces: ["Sindh", "Punjab", "Balochistan"],
    districts: ["Badin", "Hyderabad", "Multan", "Quetta"],
    sowing: "Spring: Dec–Jan; Autumn: Aug–Sep",
    harvest: "60–90 days after transplant",
    temperature: "18–29 °C",
    rainfall: "600–1250 mm equivalent",
    soil: "Well-drained loam rich in organic matter, pH 6.0–7.0",
    fertilizer: "FYM 10 t/acre + Urea 2 bags + DAP 1.5 bags + SOP 1 bag.",
    irrigation: "Drip preferred; light frequent irrigations at fruit-set.",
    weed: "Mulching + hand weeding; Pendimethalin pre-transplant.",
    pest: "Fruit borer, whitefly — pheromone traps + Spinosad.",
    disease: "Early & late blight — Mancozeb 75 WP @ 500 g/acre weekly.",
    yield: "300–500 maunds/acre",
    storage: "10–12 °C for green mature; 5–7 days shelf life ripe.",
    market: "Seasonal price swings; high-tunnel farming brings premium.",
    image: img("photo-1592924357228-91a4daadcfea"),
  },
  {
    id: "onion",
    name_en: "Onion",
    name_ur: "پیاز",
    name_roman: "Piaz",
    aliases: ["pyaz", "kanda"],
    scientific: "Allium cepa",
    emoji: "🧅",
    category: "Vegetable",
    provinces: ["Sindh", "Balochistan", "Punjab"],
    districts: ["Hyderabad", "Mirpur Khas", "Chagai", "Multan"],
    sowing: "Kharif: May–Jun; Rabi: Oct–Nov",
    harvest: "120–150 days after sowing",
    temperature: "13–24 °C for bulb development",
    rainfall: "650–750 mm",
    soil: "Sandy loam, pH 6.0–7.5",
    fertilizer: "Urea 2 bags + DAP 1.5 bags + SOP 1 bag per acre.",
    irrigation: "10–12 irrigations; stop 10 days before harvest.",
    weed: "Oxyfluorfen pre-emergence + 2 hand weedings.",
    pest: "Thrips — Fipronil 5 SC @ 200 ml/acre.",
    disease: "Purple blotch, downy mildew — Mancozeb sprays.",
    yield: "250–400 maunds/acre",
    storage: "Cure in shade 7–10 days; store in ventilated rooms.",
    market: "Frequent price shocks; export potential to Gulf.",
    image: img("photo-1620574387735-3624d75b2dbc"),
  },
  {
    id: "chili",
    name_en: "Chili",
    name_ur: "مرچ",
    name_roman: "Mirch",
    aliases: ["red chili", "lal mirch", "chilli"],
    scientific: "Capsicum annuum",
    emoji: "🌶️",
    category: "Vegetable",
    provinces: ["Sindh", "Punjab"],
    districts: ["Kunri", "Umerkot", "Mirpur Khas"],
    sowing: "Nursery Feb–Mar; transplant Apr–May",
    harvest: "Sep–November",
    temperature: "20–30 °C",
    rainfall: "600–1250 mm equivalent",
    soil: "Loam to sandy loam, pH 6.0–7.0",
    fertilizer: "FYM + Urea 2 bags + DAP 1 bag + SOP 1 bag per acre.",
    irrigation: "Drip or furrow; avoid stress at flowering.",
    weed: "Mulch + hand weeding.",
    pest: "Thrips, mites — Abamectin @ 200 ml/acre.",
    disease: "Anthracnose, wilt — seed treatment + drenching Copper oxychloride.",
    yield: "40–60 maunds dry chili/acre",
    storage: "Sun-dry to <10% moisture; store in gunny bags.",
    market: "Kunri is Asia's largest chili market; export demand.",
    image: img("photo-1583286814452-42a09fcf6fda"),
  },
  {
    id: "mango",
    name_en: "Mango",
    name_ur: "آم",
    name_roman: "Aam",
    aliases: ["aam", "mangoes", "chaunsa", "sindhri"],
    scientific: "Mangifera indica",
    emoji: "🥭",
    category: "Fruit",
    provinces: ["Sindh", "Punjab"],
    districts: ["Multan", "Rahim Yar Khan", "Mirpur Khas", "Hyderabad"],
    sowing: "Plant Feb–March or Aug–September",
    harvest: "May – August",
    temperature: "24–30 °C",
    rainfall: "750–2500 mm",
    soil: "Deep well-drained loam, pH 5.5–7.5",
    fertilizer: "FYM 40 kg + Urea 1.5 kg + DAP 1 kg + SOP 1 kg per mature tree/year.",
    irrigation: "Fortnightly Apr–Jun; withhold during flowering.",
    weed: "Basin weeding + mulching.",
    pest: "Mango hopper, fruit fly — pheromone traps + Lambda-cyhalothrin.",
    disease: "Mango malformation, anthracnose — pruning + Copper sprays.",
    yield: "80–120 maunds/acre in mature orchards",
    storage: "Cold store 12–13 °C; ripens at 20–22 °C.",
    market: "Major export: UAE, UK, EU, Iran; premium for Chaunsa & Sindhri.",
    image: img("photo-1553279768-865429fa0078"),
  },
  {
    id: "citrus",
    name_en: "Citrus (Kinnow)",
    name_ur: "کینو",
    name_roman: "Kinnow",
    aliases: ["orange", "malta", "santra", "kino"],
    scientific: "Citrus reticulata",
    emoji: "🍊",
    category: "Fruit",
    provinces: ["Punjab"],
    districts: ["Sargodha", "Bhalwal", "Toba Tek Singh"],
    sowing: "Plant Feb–Mar or Sep–Oct",
    harvest: "December – February",
    temperature: "13–35 °C",
    rainfall: "1000–1200 mm",
    soil: "Well-drained sandy loam, pH 6.0–7.5",
    fertilizer: "FYM 30 kg + Urea 1.5 kg + DAP 1 kg + SOP 1 kg per mature tree.",
    irrigation: "Every 7–15 days; drip preferred.",
    weed: "Basin weeding + mulching.",
    pest: "Citrus psylla, leaf miner — Imidacloprid systemic.",
    disease: "Citrus canker, gummosis — Bordeaux paste + trunk drenching.",
    yield: "150–200 maunds/acre in mature orchards",
    storage: "Cold store 4–6 °C for 4–8 weeks.",
    market: "Major export: Indonesia, Philippines, Middle East.",
    image: img("photo-1611080626919-7cf5a9dbab5b"),
  },
  {
    id: "gram",
    name_en: "Gram (Chickpea)",
    name_ur: "چنا",
    name_roman: "Chana",
    aliases: ["chickpea", "kabuli chana", "channa"],
    scientific: "Cicer arietinum",
    emoji: "🫘",
    category: "Pulse",
    provinces: ["Punjab", "Sindh"],
    districts: ["Bhakkar", "Layyah", "Khushab", "Tharparkar"],
    sowing: "October – November",
    harvest: "March – April",
    temperature: "10–25 °C",
    rainfall: "300–400 mm",
    soil: "Sandy loam / thal desert, pH 6.0–8.0",
    fertilizer: "DAP 1 bag + SOP 0.5 bag per acre; Rhizobium seed inoculation.",
    irrigation: "1–2 irrigations if rainfall short; usually rainfed.",
    weed: "Pendimethalin pre-emergence + 1 hand weeding.",
    pest: "Gram pod borer — NPV or Emamectin benzoate.",
    disease: "Ascochyta blight, wilt — resistant varieties + seed treatment.",
    yield: "10–20 maunds/acre",
    storage: "Dry to 9% moisture; store in sealed bags.",
    market: "Steady local demand; import gap when yields dip.",
    image: img("photo-1596591603960-8f0d4a1e2b0a"),
  },
  {
    id: "mustard",
    name_en: "Mustard / Canola",
    name_ur: "سرسوں",
    name_roman: "Sarson",
    aliases: ["canola", "raya", "toria"],
    scientific: "Brassica napus",
    emoji: "🌼",
    category: "Oilseed",
    provinces: ["Punjab", "Sindh"],
    districts: ["Faisalabad", "Sahiwal", "Sukkur"],
    sowing: "October – November",
    harvest: "March – April",
    temperature: "10–25 °C",
    rainfall: "350–450 mm",
    soil: "Well-drained loam, pH 6.0–7.5",
    fertilizer: "Urea 1.5 bags + DAP 1 bag + SOP 0.5 bag per acre.",
    irrigation: "3–4 irrigations; critical at flowering & pod-fill.",
    weed: "Isoproturon post-emergence.",
    pest: "Aphids — Imidacloprid @ 100 ml/acre.",
    disease: "Alternaria blight — Mancozeb sprays.",
    yield: "12–20 maunds/acre",
    storage: "Dry to 8% moisture before storing.",
    market: "Sold to oil mills; strong edible-oil demand.",
    image: img("photo-1502741224143-90386d7f8c82"),
  },
  {
    id: "sunflower",
    name_en: "Sunflower",
    name_ur: "سورج مکھی",
    name_roman: "Suraj Mukhi",
    aliases: ["sunflower seed"],
    scientific: "Helianthus annuus",
    emoji: "🌻",
    category: "Oilseed",
    provinces: ["Punjab", "Sindh"],
    districts: ["Multan", "Bahawalpur", "Hyderabad"],
    sowing: "Spring: Jan–Feb; Autumn: Jul–Aug",
    harvest: "100–120 days after sowing",
    temperature: "20–30 °C",
    rainfall: "500–750 mm",
    soil: "Well-drained loam, pH 6.5–7.5",
    fertilizer: "Urea 2 bags + DAP 1 bag + SOP 0.5 bag per acre.",
    irrigation: "5–6 irrigations; critical at bud & seed fill.",
    weed: "Pendimethalin + hand weeding at 30 DAS.",
    pest: "Head borer — spot spray Emamectin benzoate.",
    disease: "Head rot, downy mildew — seed treatment.",
    yield: "20–30 maunds/acre",
    storage: "Dry to 9% moisture; store in cool dry place.",
    market: "Oil mills pay premium; edible oil import substitution.",
    image: img("photo-1470549638415-0a0755be0619"),
  },
  {
    id: "banana",
    name_en: "Banana",
    name_ur: "کیلا",
    name_roman: "Kela",
    aliases: ["banana plant", "kaila"],
    scientific: "Musa acuminata",
    emoji: "🍌",
    category: "Fruit",
    provinces: ["Sindh"],
    districts: ["Thatta", "Tando Allahyar", "Nawabshah"],
    sowing: "Feb–March or Sep–October (suckers)",
    harvest: "12–15 months after planting",
    temperature: "26–30 °C",
    rainfall: "1200–2200 mm equivalent",
    soil: "Rich deep loam, pH 6.5–7.5",
    fertilizer: "FYM 25 kg + Urea 600 g + DAP 300 g + SOP 500 g per plant/year.",
    irrigation: "Weekly; drip preferred with fertigation.",
    weed: "Mulching with banana trash; hand weeding.",
    pest: "Banana weevil, nematodes — sanitation + neem cake.",
    disease: "Panama wilt, bunchy top — remove infected plants; tissue-cultured planting.",
    yield: "600–800 maunds/acre",
    storage: "Green harvest; ripen at 15–20 °C.",
    market: "Strong domestic demand; export potential to Gulf.",
    image: img("photo-1571771894821-ce9b6c11b08e"),
  },
];

export const cropById = (id: string) => CROPS.find((c) => c.id === id);
